title: Jesse Coulter
logo: "/images/headshot.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <a href="https://www.linkedin.com/in/jesse-coulter/">LinkedIn</a> 
  <br>
  <a href="/pdf/Resume%20-%20Jesse%20Coulter%20%20.pdf" class="btn btn--info">Resume</a>  
  <br>
  <a href="https://www.GitHub.com/JesseCoulter/">GitHub</a>  
  <br>
  
  
theme: jekyll-theme-minimal
